name: Upload Codecov

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 20

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:coverage
        env:
          CI: true
          NODE_ENV: ci
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
